[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate && npx tsc --noEmit false 2>&1 | tee /tmp/build.log && echo 'TSC DONE'"

[deploy]
startCommand = "npx prisma migrate deploy && node dist/index.js"